---
site_name: Libre Computer Documentation
site_url: https://j1mbl3s.github.io/libretech-web-docs
repo_url: https://github.com/j1mbl3s/libretech-web-docs
repo_name: j1mbl3s/libretech-web-docs
edit_uri: edit/main/docs/
site_description: Documentation for Libre Computer SBCs
copyright: © 2024.<span style="width:1em;display:inline-block;"></span>A <a href="https://github.com/j1mbl3s">j1mbl3s</a> production.

plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/references.md
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  logo: https://libre.computer/images/navLogo.webp
  favicon: https://libre.computer/favicon.ico
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.indexes
    - navigation.footer
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://libre.computer/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Documentation:
    - index.md

    - Hardware:
      - hardware/index.md

    - Software:
      - software/index.md

    - User Guides:
      - guides/index.md
      - Getting Started: guides/getting-started.md

      - Operating System Setup:
        - guides/setup/index.md

  - Community: https://hub.libre.computer/
  - Home: https://libre.computer/

watch:
  - includes
