---
site_name: Libre Computer Documentation
site_url: https://j1mbl3s.github.io/libretech-web-docs
repo_url: https://github.com/j1mbl3s/libretech-web-docs
repo_name: j1mbl3s/libretech-web-docs
edit_uri: edit/main/docs/
site_description: Documentation for Libre Computer SBCs
copyright: © 2024.<span style="width:1em;display:inline-block;"></span>A <a href="https://github.com/j1mbl3s">j1mbl3s</a> production.

plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/references.md
  - pymdownx.superfences
  - toc:
      permalink: true

theme:
  name: material
  logo: https://libre.computer/images/navLogo.webp
  favicon: https://libre.computer/favicon.ico
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.indexes
    - navigation.footer
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://libre.computer/

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Documentation:
    - index.md

    - Hardware:
      # - hardware/index.md
      - Libre Computer Products:
        # - hardware/boards/index.md
        - Tritium<br/>ALL-H3-CC: https://libre.computer/products/all-h3-cc/ # hardware/boards/tritium-all-h3-cc.md
        - La Frite<br/>AML-S805X-CC: https://libre.computer/products/aml-s805x-ac/ # hardware/boards/la-frite-aml-s805x-cc.md
        - Le Potato<br/>AML-S905X-CC: https://libre.computer/products/aml-s905x-cc/ # hardware/boards/le-potato-aml-s905x-cc.md
        - Sweet Potato<br/>AML-S905X-CC-V2: https://libre.computer/products/aml-s905x-cc-v2/ # hardware/boards/sweet-potato-aml-s905x-cc-v2.md
        - Solitude<br/>AML-S905D3-CC: https://libre.computer/products/aml-s905d3-cc/ # hardware/boards/solitude-aml-s905d3-cc.md
        - Alta<br/>AML-A311D-CC: https://libre.computer/products/aml-a311d-cc/ # hardware/boards/alta-aml-a311d-cc.md
        - Renegade<br/>ROC-RK3328-CC: https://libre.computer/products/roc-rk3328-cc/ # hardware/boards/renegade-roc-rk3328-cc.md
        - Renegade Elite<br/>ROC-RK3399-PC: https://libre.computer/products/roc-rk3399-pc/ # hardware/boards/renegade-elite-roc-rk3399-pc.md

    - Software:
      # - software/index.md
      - Operating Systems:
        # - software/os/index.md
        - Debian: https://hub.libre.computer/t/debian-11-bullseye-for-libre-computer-boards/230 # software/os/debian.md
        - Fedora: https://hub.libre.computer/t/fedora-for-libre-computer-boards/3225 # software/os/fedora.md
        - Ubuntu: https://hub.libre.computer/t/ubuntu-22-04-1-jammy-lts-for-libre-computer-boards/20 # software/os/ubuntu.md
        - OpenSUSE: https://hub.libre.computer/t/opensuse-for-libre-computer-boards/3226 # software/os/opensuse.md
        - Raspbian: https://hub.libre.computer/t/raspbian-11-bullseye-for-libre-computer-boards/82 # software/os/raspbian.md
        - Batocera: https://hub.libre.computer/t/batocera-linux-for-libre-computer-boards/272 # software/os/batocera.md
        - Lakka: https://hub.libre.computer/t/lakka-for-libre-computer-boards/231 # software/os/lakka.md
        - CoreELEC: https://hub.libre.computer/t/coreelec-for-libre-computer-amlogic-boards/234 # software/os/corelec.md
        - LibreELEC: https://hub.libre.computer/t/libreelec-for-libre-computer-boards/233 # software/os/libreelec.md
        - Android: https://hub.libre.computer/t/android-for-libre-computer-boards/232 # software/os/android.md
        - Armbian: https://www.armbian.com/download/?tx_maker=libre-computer # software/os/armbian.md

      - Tools:
        # - software/tools/index.md
        - libretech-flash-tool: https://github.com/libre-computer-project/libretech-flash-tool # software/tools/libretech-flash-tool.md
        - libretech-slipstream: https://github.com/libre-computer-project/libretech-slipstream # software/tools/libretech-slipstream.md
        - libretech-wiring-tool: https://github.com/libre-computer-project/libretech-wiring-tool # software/tools/libretech-wiring-tool.md

    - User Guides:
      - guides/index.md
      - Getting Started: guides/getting-started.md

      - Operating System Setup:
        - guides/setup/index.md

  - Community: https://hub.libre.computer/
  - Home: https://libre.computer/

watch:
  - includes
