---
name: Build and deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create artifact
        run: mkdocs build -s
  
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
  
  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: Deploy pages artifact
        id: deployment
        uses: actions/deploy-pages@v4
